### ISSUE TITLE
opengl-testing fails to build on Fedora due to SELinux

### ISSUE THREAD

**Issue by shaded-enmity** [shaded-enmity/docker-hica#11]
Building the `ubuntu:precise` based Docker image fails with:

```
Step 9 : RUN useradd docker
 ---> Running in d9a06a97e1c5
useradd: failure while writing changes to /etc/passwd
```

Doing `setenforce 0` workarounds the problem.

`sudo ausearch -sv no --start recent`

Does not show any recent audit messages, so I guess whatever happens is swallowed by noaudit policy.

Note that minimal reproducer based on Fedora:22 image works fine:

```
Step 0 : FROM fedora:22
 ---> 0bdadfe8d1ac
Step 1 : RUN useradd docker
 ---> Running in 38e550d98579
 ---> 04bb391d810c
```

@rhatdan any ideas?

**Comment by shaded-enmity** [comment]
Some more analysis.
This happens only with `ubuntu:precise` I couldn't replicate it with other base images.

Strace of tha failing execution:

```
/* this section repeats for any opened file */
6912  gettid()                          = 13
6912  open("/proc/self/task/13/attr/current", O_RDONLY) = 9
6912  read(9, "system_u:system_r:svirt_lxc_net_"..., 4095) = 47
6912  close(9)                          = 0
6912  close(8)                          = 0
6912  munmap(0x7f3512ac3000, 4096)      = 0
6912  fgetxattr(7, "security.selinux", "system_u:object_r:svirt_sandbox_file_t:s0:c439,c911", 255) = 52
6912  read(7, "root:*:16728:0:99999:7:::\ndaemon"..., 4096) = 504
6912  read(7, "", 4096)                 = 0

/*  here happens the actual error  */
6912  gettid()                          = 13
6912  open("/proc/self/task/13/attr/fscreate", O_RDONLY) = 8
6912  read(8, "", 4095)                 = 0
6912  close(8)                          = 0
6912  gettid()                          = 13
6912  open("/proc/self/task/13/attr/fscreate", O_RDWR) = 8
6912  write(8, "system_u:object_r:svirt_sandbox_"..., 52) = -1 EACCES (Permission denied)
6912  close(8)                          = 0
```

The `fscreate` call here is documented at:
https://lwn.net/Articles/28222/

**Comment by rhatdan** [comment]
Is the machine SELinux enabled?  If yes then you are probably being blocked by SELinux from setting the fscreate. Check ausearch -m avc -ts recent 

For avcs/

**Comment by shaded-enmity** [comment]
@rhatdan yes, this is Fedora 22 host and the minimal reproducer is:

```
$ docker run ubuntu:precise useradd johnfoo
useradd: failure while writing changes to /etc/passwd
```

ausearch returns
`<no matches>`

I think it's no-audit.

**Comment by shaded-enmity** [comment]
libselinux in `precise` and below (`lucid` also) is very outdated and the base image doesn't work on SELinux enabled hosts.
